### ISSUE TITLE
Remove our names from FakeNameGeneratorService

### ISSUE THREAD

**Issue by adrien-nf** [tylp/memo-draw#111]
I do not feel comfortable having my name in there, and feel as if it is not professional. Should we remove all our names? Maybe put on silly names, jokes, puns ?..

**Comment by tylp** [comment]
Agreed, but I can't see this service in main. This should be fixed in the affected branch.

**Comment by tylp** [comment]
> Agreed, but I can't see this service in main. This should be fixed in the affected branch.

Nevemind, found it.

**Comment by adrien-nf** [comment]
Sounds good to me, I'll do it later, unless you want to.

**Comment by tylp** [comment]
> Sounds good to me, I'll do it later, unless you want to.

I'll do it now... Unless u want to do it now ?? haha jk... unless ?
