### ISSUE TITLE
Design of the graphic charter and mockups

### ISSUE THREAD

**Issue by nathangobinet** [tylp/memo-draw#13]
- [x] Moodboard
- [x] Logo
- [x] Grapic charter 
  - [x]  Typo
  - [x] Colors
- [x] Mockup
  - [x] Home
  - [x] Lobby
  - [x] Game drawer
  - [x] Game viewer
  - [x] Game viewer vote
  - [x] Game eliminated
- [x] Avatar

**Comment by adrien-nf** [comment]
Wouldn't the "Game eliminated" mockup simply be the same as "Game viewer" @vbouillennec @cyrilgourgouillon @nathangobinet @tylp ?

**Comment by adrien-nf** [comment]
Assumed yes.
