### ISSUE TITLE
UI implementation

### ISSUE THREAD

**Issue by tylp** [tylp/memo-draw#21]
Currently looking for different ways to build the UI.

I am still wondering if we should go : 

1. Pure SASS, [defining the color palette in a theme](https://www.zaratan.fr/next-refactor-theme-scss) and [using a SCSS file per component](https://www.freecodecamp.org/news/how-to-use-sass-with-css-modules-in-next-js/).
2. Go with [Tailwind](https://tailwindcss.com/), which seems to be a good option from what i saw online.

What do you think ?

**Comment by cyrilgourgouillon** [comment]
Tailwind, the second option, sounds great to me :+1:.
From what i've read in their documentation, it's heavily customisable and visually nice.

So why not go for it.

**Comment by tylp** [comment]
@adrien-nf

**Comment by adrien-nf** [comment]
I'd say Tailwind would be the perfect middle ground between raw SASS and a full library. Tailwind sounds good to me!
