### ISSUE TITLE
Create homepage components

### ISSUE THREAD

**Issue by cyrilgourgouillon** [tylp/memo-draw#24]
- [x] Title
- [x] Button
- [x] RuleItem
- [x] ProfileSettings

**Comment by tylp** [comment]
Working on the title

**Comment by tylp** [comment]
ProfileSettings done in https://github.com/tylp/memo-draw/commit/0349d6b94adb29c83322e57873760211db74ae5b

**Comment by tylp** [comment]
Button added in https://github.com/tylp/memo-draw/commit/c83ca1c50f7eb8ea0f98787a88144554b9035f56
