### ISSUE TITLE
Most of the engine sockets must be broadcast not full emit

### ISSUE THREAD

**Issue by nathangobinet** [tylp/memo-draw#275]
We don't want to send a socket to the player who emitted it. So we should use the broadcast function instead of full emit. See https://github.com/nathangobinet/react-draw/blob/master/server.js

**Comment by adrien-nf** [comment]
I wouldn't say that most of them need to be broadcasted, but yeah, I've been lazy on this part, and we could definitely optimize the behaviour of the sockets. I say, let's discuss this next meeting.
