### ISSUE TITLE
Change naming convention to pascal

### ISSUE THREAD

**Issue by tylp** [tylp/memo-draw#28]
Since we are using the Airbnb guidelines for our eslint, we probably should use the pascal convention [acording to their documentation](https://airbnb.io/javascript/react/#naming).

**Comment by cyrilgourgouillon** [comment]
[Commit](https://github.com/tylp/memo-draw/commit/01b74038ef7c7c418075e776978b2a51872ecbba)

**Comment by tylp** [comment]
Updated files and folder names in aeecd77e30b1745c96f15fcafa0eb1e9eeb281c4

**Comment by tylp** [comment]
At this point, should we also rename the other folders in pascal (eg; hooks --> Hooks) ? Or should we apply this convention ton only the pages and components ?

**Comment by adrien-nf** [comment]
> At this point, should we also rename the other folders in pascal (eg; hooks --> Hooks) ? Or should we apply this convention ton only the pages and components ?

I'd say, rename folders too, this way we won't have to mentally switch between two cases.

@tylp

**Comment by adrien-nf** [comment]
Actually, folders are fine.
