### ISSUE TITLE
refactor theme colors 

### ISSUE THREAD

**Issue by tylp** [tylp/memo-draw#30]
We should refactor the theme color names to follow the [official pattern](https://tailwindcss.com/docs/theme#colors) with 10 shades.

Example:

```json
blue: {
  'darker-blue': '#004063',
  'blue': '#006DBB',
  'light-blue': '#00BAE3',
  'lighter-blue': '#33C5F5',
}
```

should become something like

```json
blue: {
  100: '#004063',
  200: x,
  300: x;
  400: x,
  500: '#006DBB',
  600: x,
  700: '#00BAE3',
  800: x,
  900: '#33C5F5',
}
```

**Comment by cyrilgourgouillon** [comment]
I don't think it's mandatory to have 10 shades for each color we use.
I'd say that it's sufficient to only have colors that match our graphic chart, like in this [tailwindcss example](https://tailwindcss.com/docs/customizing-colors#custom-colors).

What do You think ?

**Comment by tylp** [comment]
I agree, closing this.
