### ISSUE TITLE
It should be possible to press enter instead of clicking "Done" on index page

### ISSUE THREAD

**Issue by adrien-nf** [tylp/memo-draw#45]
![image](https://user-images.githubusercontent.com/22148893/128422300-0e78bc1e-c524-42c0-a90f-56b620251f49.png)
No one wants to use its mouse to click... Let's make it so that no one has to!

**Comment by cyrilgourgouillon** [comment]
Done with 66a648f701e32db0d5f592edb9c7af031b579f84
